# Simulated daily request to your render project so that the service doesn't go down
name: Half-hourly render ping

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://codifier-xrzs.onrender.com/
